main = ".open-next/worker.js"
name = "webosumania"
compatibility_date = "2025-05-18"
compatibility_flags = ["nodejs_compat"]
kv_namespaces = [
    { binding = "TOKENS", id = "d0c50871fb9a40359ca080d6754d99f1" },
    { binding = "BEATMAP_SETS", id = "a350f70271374c7cb85e6597e64dcb6c" },
    { binding = "BEATMAP_SET_DATA", id = "45de3d1e808249e284f590cf8891ce4d" },

]
[assets]
directory = ".open-next/assets"
binding = "ASSETS"
[observability.logs]
enabled = true
